version: "3.8"

name: ${PROJECT_NAME}

volumes:
  db-data:
    name: ${DB_VOLUME_NAME}
  db-adminer-data:
    name: ${ADMINER_VOLUME_NAME}

services:
  # Adminer
  adminer:
    image: adminer
    container_name: ${ADMINER_CONTAINER_NAME}
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db:${DB_SERVER_NAME}
    restart: always
    pull_policy: build

  # MySQL DB
  db:
    image: mariadb:${DB_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - ${DB_PORT}:3306
    expose:
      - "3306"
    restart: always
    pull_policy: build
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PWD}
      MARIADB_ROOT_PASSWORD: ${DB_PWD}
